service: ppstellar

provider:
  name: aws
  profile: personal
  region: us-east-1
  runtime: nodejs6.10
  stage: dev

functions:
  hello:
    handler: lib/lambdas.hello
    events:
    - http: GET hello
  startPrivatePayment:
    handler: lib/lambdas.startPrivatePayment
    events:
    - http: POST start_private_payment
  getMixTransaction:
    handler: lib/lambdas.getMixTransaction
    events:
    - http: GET get_mix_transaction
  signMixTransaction:
    handler: lib/lambdas.signMixTransaction
    events:
    - http: POST sign_mix_transaction
  createMixTransaction:
    handler: lib/lambdas.createMixTransaction
    events: []


plugins:
- serverless-offline
