service: ppstellar

provider:
  name: aws
  profile: personal
  region: us-east-1
  runtime: nodejs6.10
  stage: dev

functions:
  hello:
    handler: lib/lambdas.hello
    events:
    - http: POST hello
  startPrivatePayment:
    handler: lib/lambdas.startPrivatePayment
    events:
    - http: POST start_private_payment
  getPrivatePayment:
    handler: lib/lambdas.getPrivatePayment
    events:
    - http: POST get_private_payment
  getMixTransaction:
    handler: lib/lambdas.getMixTransaction
    events:
    - http: POST get_mix_transaction
  postSignedTransaction:
    handler: lib/lambdas.postSignedTransaction
    events:
    - http: POST post_signed_transaction


plugins:
- serverless-offline
