service: ppstellar

provider:
  name: aws
  profile: personal
  region: us-east-1
  runtime: nodejs6.10
  stage: dev

functions:
  startPrivatePayment:
    handler: lib/lambda/startPrivatePayment.entry
    events:
    - http: POST private_payment
  getUnsignedMixTx:
    handler: lib/lambda/getUnsignedMixTx.entry
    events:
    - http:
        path: mix_tx/{id}/unsigned
        method: get
        request:
          parameters:
            paths:
              id: true
  signMixTx:
    handler: lib/lambda/signMixTx.entry
    events:
    - http:
        path: mix_tx/{id}/signature
        method: post
        request:
          parameters:
            paths:
              id: true
  getSignedMixTx:
    handler: lib/lambda/getSignedMixTx.entry
    events:
    - http:
        path: mix_tx/{id}/signed
        method: get
        request:
          parameters:
            paths:
              id: true

  initiateMixes:
    handler: lib/lambda/initiateMixes.entry
    events:
    - schedule: rate(1 second)
    - http: POST internal/initiate_mixes
    environment:
      START_MIX_URI: http://localhost:4000/internal/start_mix
  startMix:
    handler: lib/lambda/startMix.entry
    events:
    - http: POST internal/start_mix


plugins:
- serverless-offline
