service: ppstellar

provider:
  name: aws
  profile: personal
  region: us-east-1
  runtime: nodejs6.10
  stage: dev

functions:
  startPrivatePayment:
    handler: lib/lambda/startPrivatePayment.entry
    events:
    - http: POST private_payment
  getMixTx:
    handler: lib/lambda/getMixTx.entry
    events:
    - http:
        path: private_payment/{id}/tx
        method: get
        request:
          parameters:
            paths:
              id: true
  signMixTx:
    handler: lib/lambda/signMixTx.entry
    events:
    - http:
        path: private_payment/{id}/sign
        method: post
        request:
          parameters:
            paths:
              id: true

  initiateMixes:
    handler: lib/lambda/initiateMixes.entry
    events:
    - schedule: rate(1 second)
    - http: POST internal/initiate_mixes


plugins:
- serverless-offline
